// This file is automatically generated. Do not edit it directly.
// ⚠️ DEPRECATED: Supabase has been replaced with Firebase
// This client is disabled to prevent connection timeout errors
// Do not use Supabase anywhere in the codebase - use Firebase instead

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL) {
  console.warn('[DEPRECATED] VITE_SUPABASE_URL is not defined. Supabase is no longer used.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[DEPRECATED] VITE_SUPABASE_PUBLISHABLE_KEY is not defined. Supabase is no longer used.');
}

// DISABLED: Supabase client disabled - use Firebase instead
// export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
//   auth: {
//     persistSession: true,
//     storageKey: 'supabase.auth.token',
//     storage: typeof window !== 'undefined' ? window.localStorage : undefined,
//   },
// });

// Throw error if anyone tries to use it
export const supabase = new Proxy({}, {
  get: () => {
    throw new Error('❌ Supabase has been deprecated and replaced with Firebase. Please migrate your code to use Firebase instead.');
  }
});
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});